# -*- coding: utf-8 -*-
"""aviation-disruption-country-analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NFUj7mrsBeuEJkAZE4vuDCrAjW3yzkm-
"""

import os
import zipfile
from pathlib import Path

import pandas as pd
import streamlit as st
from kaggle.api.kaggle_api_extended import KaggleApi

st.set_page_config(page_title="Global Aviation Disruption Analyzer", layout="wide")

DATASET = "zkskhurram/global-civil-aviation-disruption2026-iranus-war"
FILE_NAME = "airline_losses_estimate.csv"
DOWNLOAD_DIR = Path("data_cache")


@st.cache_data(ttl=7 * 24 * 60 * 60)
def load_data():
    os.environ["KAGGLE_USERNAME"] = st.secrets["kaggle"]["username"]
    os.environ["KAGGLE_KEY"] = st.secrets["kaggle"]["key"]

    DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)

    api = KaggleApi()
    api.authenticate()

    api.dataset_download_file(
        dataset=DATASET,
        file_name=FILE_NAME,
        path=str(DOWNLOAD_DIR),
        force=True,
        quiet=True,
    )

    csv_path = DOWNLOAD_DIR / FILE_NAME
    zip_path = DOWNLOAD_DIR / f"{FILE_NAME}.zip"

    if zip_path.exists():
        with zipfile.ZipFile(zip_path, "r") as zf:
            zf.extractall(DOWNLOAD_DIR)

    df = pd.read_csv(csv_path)
    return df


df = load_data()

st.title("Global Aviation Disruption Analyzer")

countries = sorted(df["country"].dropna().unique())
country = st.selectbox("Select a country", countries)

filtered = df[df["country"] == country]

table = filtered[
    [
        "airline",
        "estimated_daily_loss_usd",
        "cancelled_flights",
        "rerouted_flights",
        "passengers_impacted",
    ]
].rename(
    columns={
        "airline": "Airline",
        "estimated_daily_loss_usd": "Daily Loss (USD)",
        "cancelled_flights": "Cancelled Flights",
        "rerouted_flights": "Rerouted Flights",
        "passengers_impacted": "Passengers Impacted",
    }
)

st.subheader(f"Airlines affected in {country}")
st.dataframe(table, use_container_width=True)

st.subheader("Summary")
col1, col2, col3, col4 = st.columns(4)

col1.metric("Total Loss (USD)", f"{filtered['estimated_daily_loss_usd'].sum():,}")
col2.metric("Cancelled Flights", int(filtered["cancelled_flights"].sum()))
col3.metric("Rerouted Flights", int(filtered["rerouted_flights"].sum()))
col4.metric("Passengers Impacted", int(filtered["passengers_impacted"].sum()))